### ISSUE TITLE
Menghapus Kode yg Tidak Perlu

### ISSUE THREAD

**Issue by jefrydco** [yoshivirgiawan/Tugas-Webinar-VueJs#1]
Hi Mas Yoshi, teirma kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Yoshi.

Mas juga sudah menggunakan kerangka kerja CSS Bootstrap di aplikasi pencari teks di video YouTube ini. Luar biasa Mas!

Namun saya ada 1 saran kecil Mas yakni menghapus kode yg tidak perlu. Pada berkas `index.html` baris ke 167-169 ini Mas menyertakan perpustakan JavaScript eksternal jQuery, Popper dan Bootstrap.

https://github.com/yoshivirgiawan/Tugas-Webinar-VueJs/blob/4b179fb1a1c5c8c9487bfddb9ca0bb2214438f2b/index.html#L167-L169

Menurut saya ketiga perpustakaan JavaScript tersebut dapat dihapus Mas, karena saya lihat di aplikasi ini tidak menggunakannya. Bahkan Bootstrap pun hanya digunakan kerangka kerja CSS nya saja.

Semangat Mas! 😄

**Comment by yoshivirgiawan** [comment]
Baik, terima kasih atas sarannya mas

Pada tanggal Rab, 12 Agt 2020 18:11, Jefry Dewangga <
notifications@github.com> menulis:

**Comment by jefrydco** [comment]
Terima kasih kembali Mas, saya akan membiarkan isu ini terbuka ya Mas, nanti kalau Mas ada waktu dan berkenan untuk memperbaiki Mas bisa menutup isu ini. Semangat selalu Mas! 😄

**Comment by yoshivirgiawan** [comment]
Selamat siang mas, penulisan kodenya sudah saya perbaiki sesuai saran yang Mas Jefry berikan, terima kasih telah meluangkan waktunya untuk mengoreksi penulisan kode saya, untuk ke depannya saya akan tingkatkan lagi, terima kasih mas
